# Scouter Java Agent Configuration

# Scouter Server 연결
net_collector_ip=scouter-server
net_collector_udp_port=6100
net_collector_tcp_port=6100

# Trace
trace_interservice_enabled=true
profile_step_max_count=1024
xlog_sampling_enabled=false

# Hook
hook_method_patterns=com.middleware.demo.*.*
hook_service_patterns=com.middleware.demo.controller.*.*

# HTTP
trace_http_client_ip_header_key=X-Forwarded-For
