# Scouter Server Configuration

# Network
net_tcp_listen_port=6100
net_http_port=6180

# DB
db_dir=./database

# Log
log_dir=./logs
log_rotation_enabled=true
log_keep_days=7

# Object
obj_deadtime=30000
